AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  Function:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: target/Curtains-1.0-SNAPSHOT.jar
      Handler: curtains.DailyMessageHandler::eventHandler
      Runtime: java11
      MemorySize: 192
      Timeout: 40
      Environment:
        Variables:
          GUARDIAN_OPEN_PLATFORM_API_KEY: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          NEWSAPI_API_KEY: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          RECEIVER_PHONE_NUMBER: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          TWILIO_ACCOUNT_SID: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          TWILIO_AUTH_TOKEN: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          TWILIO_PHONE_NUMBER: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
          WTTR_LOCATION: HIDDEN-FOR-REPO-SET-IN-LAMBDA-CONSOLE
